services:
  mariadb:
    image: "mariadb:latest"
    restart: 'unless-stopped'
    volumes:
      - "db_data:/var/lib/mysql"
      - "db_config:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      start_period: 20s
      start_interval: 1s
      interval: 30s
      timeout: 5s

  backend:
    build: ./backend
    restart: 'unless-stopped'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "42069:42069"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  db_data:
  db_config: