services:
  mariadb:
    image: "mariadb:latest"
    restart: 'unless-stopped'
    volumes:
      - "db_data:/var/lib/mysql"
      - "db_config:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - nginx
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      start_period: 20s
      start_interval: 1s
      interval: 30s
      timeout: 5s

  backend:
    build: ./backend
    restart: 'unless-stopped'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - nginx
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.Dev
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
    tty: true
    networks:
      - nginx
    command: npm run dev -- --host

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1420:1420"
    networks:
      - nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - frontend
      - backend

networks:
  nginx:

volumes:
  db_data:
  db_config: