services:
  mariadb:
    image: "mariadb:latest"
    volumes:
      - "db_data:/var/lib/mysql"
      - "db_config:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      start_period: 20s
      start_interval: 1s
      interval: 30s
      timeout: 5s

  backend:
    build: ./backend
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "42069:42069"
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
    ports:
      - "5173:5173"
    tty: true
    command: npm run dev -- --host

volumes:
  db_data:
  db_config: