services:
  mariadb:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      start_period: 20s
      start_interval: 1s
      interval: 30s
      timeout: 5s

  backend:
    build:
      dockerfile: backend/Test.Dockerfile
      context: .
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
      - ./backend/pom.xml:/app/pom.xml
      - ./.m2:/root/.m2
    command: ["mvn", "test"]