name: Continuous Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    strategy:
      matrix:
        item:
          [
            { df_path: ./frontend, image: "${{ github.repository}}/hausfix-frontend" },
            { df_path: ./backend, image: "${{ github.repository }}/hausfix-backend" },
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.item.image }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.item.df_path }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: URL=${{ secrets.BACKEND_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        if: github.event_name != 'pull_request'
        with:
          subject-name: ${{ env.REGISTRY }}/${{ matrix.item.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Update via Webhook
        uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK }}
